var aNavItemData =[
    [
		{
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 1',
        	price:'3299',
        	tag:'新品'
        },
        {
        	url:'http://www.taobao.com',
        	img:'img/222.png',
        	name:'小米MIX 1',
        	price:'3299',
        	// tag:'新品'
        },
        {
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 1',
        	price:'3299',
        	tag:'新品'
        },
    ],
     // 红米
    [
       {
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 2',
        	price:'3299',
        	tag:'新品'
        },
        {
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 2',
        	price:'3299',
        	tag:'新品'
        },
        {
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 2',
        	price:'3299',
        	// tag:'新品'
        },
    ],
     // 电视
    [
       {
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 3',
        	price:'3299',
        	tag:'新品'
        },
        {
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 3',
        	price:'3299',
        	// tag:'新品'
        },
        {
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 3',
        	price:'3299',
        	tag:'新品'
        },
    ],
     // 笔记本
    [
       {
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 4',
        	price:'3299',
        	// tag:'新品'
        },
        {
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 4',
        	price:'3299',
        	tag:'新品'
        },
        {
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 4',
        	price:'3299',
        	// tag:'新品'
        },
    ],
     // 盒子
    [
       {
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 5',
        	price:'3299',
        	// tag:'新品'
        },
        {
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 5',
        	price:'3299',
        	tag:'新品'
        },
        {
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 5',
        	price:'3299',
        	// tag:'新品'
        },
    ],
     // 新品
    [
       {
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 6',
        	price:'3299',
        	// tag:'新品'
        },
        {
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 6',
        	price:'3299',
        	tag:'新品'
        },
        {
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 6',
        	price:'3299',
        	tag:'新品'
        },
    ],
     // 路由器
    [
       {
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 7',
        	price:'3299',
        	// tag:'新品'
        },
        {
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 7',
        	price:'3299',
        	tag:'新品'
        },
        {
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 7',
        	price:'3299',
        	tag:'新品'
        },
    ],
     // 智能硬件
    [
       {
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 2',
        	price:'3299',
        	// tag:'新品'
        },
        {
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 2',
        	price:'3299',
        	tag:'新品'
        },
        {
        	url:'http://www.taobao.com',
        	img:'img/111.png',
        	name:'小米MIX 2',
        	price:'3299',
        	tag:'新品'
        },
    ],
];

var aShowItemData = [
   [
       {
            url:'http://www.taobao.com',
            img:'img/shouji1.png',
            name:'小米MIX1',
       },
       {
            url:'http://www.taobao.com',
            img:'img/shouji1.png',
            name:'小米MIX1',
       },
       {
            url:'http://www.taobao.com',
            img:'img/shouji1.png',
            name:'小米MIX1',
       }
   ],
   [
       {
            url:'http://www.taobao.com',
            img:'img/shouji2.png',
            name:'小米MIX2',
       },
       {
            url:'http://www.taobao.com',
            img:'img/shouji2.png',
            name:'小米MIX2',
       },
       {
            url:'http://www.taobao.com',
            img:'img/shouji2.png',
            name:'小米MIX2',
       },
   ],
   [
       {
            url:'http://www.taobao.com',
            img:'img/shouji3.png',
            name:'小米MIX3',
       },
       {
            url:'http://www.taobao.com',
            img:'img/shouji3.png',
            name:'小米MIX3',
       },
       {
            url:'http://www.taobao.com',
            img:'img/shouji3.png',
            name:'小米MIX3',
       },
   ],
   [
       {
            url:'http://www.taobao.com',
            img:'img/shouji4.png',
            name:'小米MIX4',
       },
       {
            url:'http://www.taobao.com',
            img:'img/shouji4.png',
            name:'小米MIX4',
       },
       {
            url:'http://www.taobao.com',
            img:'img/shouji4.png',
            name:'小米MIX4',
       },
   ],
   [
       {
            url:'http://www.taobao.com',
            img:'img/shouji1.png',
            name:'小米MIX5',
       },
       {
            url:'http://www.taobao.com',
            img:'img/shouji1.png',
            name:'小米MIX5',
       },
       {
            url:'http://www.taobao.com',
            img:'img/shouji1.png',
            name:'小米MIX5',
       },
   ],
   [
       {
            url:'http://www.taobao.com',
            img:'img/shouji2.png',
            name:'小米MIX6',
       },
       {
            url:'http://www.taobao.com',
            img:'img/shouji2.png',
            name:'小米MIX6',
       },
       {
            url:'http://www.taobao.com',
            img:'img/shouji2.png',
            name:'小米MIX6',
       },
   ],
   [
       {
            url:'http://www.taobao.com',
            img:'img/shouji3.png',
            name:'小米MIX7',
       },
       {
            url:'http://www.taobao.com',
            img:'img/shouji3.png',
            name:'小米MIX7',
       },
       {
            url:'http://www.taobao.com',
            img:'img/shouji3.png',
            name:'小米MIX7',
       },
   ],
   [
       {
            url:'http://www.taobao.com',
            img:'img/shouji4.png',
            name:'小米MIX8',
       },
       {
            url:'http://www.taobao.com',
            img:'img/shouji4.png',
            name:'小米MIX8',
       },
       {
            url:'http://www.taobao.com',
            img:'img/shouji4.png',
            name:'小米MIX8',
       },
   ],
   [
       {
            url:'http://www.taobao.com',
            img:'img/shouji5.png',
            name:'小米MIX9',
       },
       {
            url:'http://www.taobao.com',
            img:'img/shouji5.png',
            name:'小米MIX9',
       },
       {
            url:'http://www.taobao.com',
            img:'img/shouji5.png',
            name:'小米MIX9',
       },
   ],
   [
       {
            url:'http://www.taobao.com',
            img:'img/shouji5.png',
            name:'小米MIX10',
       },
       {
            url:'http://www.taobao.com',
            img:'img/shouji5.png',
            name:'小米MIX10',
       },
       {
            url:'http://www.taobao.com',
            img:'img/shouji5.png',
            name:'小米MIX10',
       },
   ]
];

var aTopItemData = [
    [
        {
            url:'http://www.taobao.com',
            img:'img/jiadian1.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian2.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian3.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian4.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian5.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
           flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian1.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian1.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            top:{
                url:'http://www.taobao.com',
                img:'img/jiadian5.png',
                name:'小米摄像机',
                price:'1899',
            },
            bottom:{
                url:'http://www.taobao.com',
                img:'img/jiadian6.png',
                txt:'浏览更多',
                tag:'热门',
            }
        }
    ],    
    [
        {
            url:'http://www.taobao.com',
            img:'img/jiadian4.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian3.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian2.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian3.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian1.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
           flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian1.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian1.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            top:{
                url:'http://www.taobao.com',
                img:'img/jiadian5.png',
                name:'小米摄像机',
                price:'1899',
            },
            bottom:{
                url:'http://www.taobao.com',
                img:'img/jiadian6.png',
                txt:'浏览更多',
                tag:'热门',
            }
        }
    ],
    [
        {
            url:'http://www.taobao.com',
            img:'img/jiadian1.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian3.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian3.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian4.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian4.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
           flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian1.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian1.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            top:{
                url:'http://www.taobao.com',
                img:'img/jiadian5.png',
                name:'小米摄像机',
                price:'1899',
            },
            bottom:{
                url:'http://www.taobao.com',
                img:'img/jiadian6.png',
                txt:'浏览更多',
                tag:'热门',
            }
        }
    ],
    [
        {
            url:'http://www.taobao.com',
            img:'img/jiadian1.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian1.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian1.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian1.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian1.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
           flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian1.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            url:'http://www.taobao.com',
            img:'img/jiadian1.png',
            name:'小米8 4GB+64GB',
            desc:'变焦双摄，4轴防抖，骁龙835处理器',
            price:'2299',
            del:'3699',
            flag:'减1000元',
            box:{
                recontent:'一直想买个小米电视，果然不失所望，大爱',
                author:'来自于1471476770用户的评价'
            }
        },
        {
            top:{
                url:'http://www.taobao.com',
                img:'img/jiadian5.png',
                name:'小米摄像机',
                price:'1899',
            },
            bottom:{
                url:'http://www.taobao.com',
                img:'img/jiadian6.png',
                txt:'浏览更多',
                tag:'热门',
            }
        }
    ],
];
